// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type APIKeyHashData struct {
	// Hash of the key ID.
	KeyIDHash *string `json:"keyIdHash,omitempty"`
	// Last 4 digits of the key ID. Algorithm: sha256sum | tr -d '-' | xxd -r -p | base64
	KeyIDSuffix *string `json:"keyIdSuffix,omitempty"`
	// Hash of the key secret. Algorithm: sha256sum | tr -d '-' | xxd -r -p | base64
	KeySecretHash *string `json:"keySecretHash,omitempty"`
}
