// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type APIKeyPostResponse struct {
	Key *APIKey `json:"key,omitempty"`
	// Generated key ID. Provided only if there was no 'hashData' in the request.
	KeyID *string `json:"keyId,omitempty"`
	// Generated key secret. Provided only if there was no 'hashData' in the request.
	KeySecret *string `json:"keySecret,omitempty"`
}
