// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type IPAccessListEntry struct {
	// IPv4 address or IPv4 CIDR to allow access from
	Description string `json:"description"`
	// IP or CIDR
	Source string `json:"source"`
}
