// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// MemberPatchRequestRole - Role of the member in the organization.
type MemberPatchRequestRole string

const (
	MemberPatchRequestRoleAdmin     MemberPatchRequestRole = "admin"
	MemberPatchRequestRoleDeveloper MemberPatchRequestRole = "developer"
)

func (e MemberPatchRequestRole) ToPointer() *MemberPatchRequestRole {
	return &e
}

func (e *MemberPatchRequestRole) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "admin":
		fallthrough
	case "developer":
		*e = MemberPatchRequestRole(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MemberPatchRequestRole: %v", v)
	}
}

type MemberPatchRequest struct {
	// Role of the member in the organization.
	Role *MemberPatchRequestRole `json:"role,omitempty"`
}
