// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ServicePatchRequest struct {
	IPAccessList *IPAccessListPatch `json:"ipAccessList,omitempty"`
	// Name of the service.
	Name *string `json:"name,omitempty"`
}
