// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ServiceScalingPatchRequest struct {
	// When set to true the service is allowed to scale down to zero when idle. Always true for development services.
	IdleScaling *bool `json:"idleScaling,omitempty"`
	// Set minimum idling timeout (in minutes). Must be &gt;= 5 minutes.
	IdleTimeoutMinutes *float64 `json:"idleTimeoutMinutes,omitempty"`
	// Maximum total memory of all workers during auto-scaling in Gb. Available only for 'production' services. Must be a multiple of 12 and lower than 360 for non paid services or 720 for paid services.
	MaxTotalMemoryGb *float64 `json:"maxTotalMemoryGb,omitempty"`
	// Minimum total memory of all workers during auto-scaling in Gb. Available only for 'production' services. Must be a multiple of 12 and greater than 24.
	MinTotalMemoryGb *float64 `json:"minTotalMemoryGb,omitempty"`
}
