// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ServicePasswordPatchResponse struct {
	// New service password. Provided only if there was no 'newPasswordHash' in the request
	Password *string `json:"password,omitempty"`
}
