// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ServicePostResponse struct {
	// Password for the newly created service.
	Password *string  `json:"password,omitempty"`
	Service  *Service `json:"service,omitempty"`
}
