// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ServicePasswordPatchRequest struct {
	// Optional password hash. Used to avoid password transmission over network. If not provided a new password is generated and is provided in the response. Otherwise this hash is used. Algorithm: sha256sum | tr -d '-' | xxd -r -p | base64
	NewPasswordHash *string `json:"newPasswordHash,omitempty"`
}
