// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type IPAccessListEntry struct {
	Description types.String `tfsdk:"description"`
	Source      types.String `tfsdk:"source"`
}
