// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"clickhouse/internal/sdk/pkg/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *UserResourceModel) ToCreateSDKType() *shared.InvitationPostRequest {
	email := r.Email.ValueString()
	role := shared.InvitationPostRequestRole(r.Role.ValueString())
	out := shared.InvitationPostRequest{
		Email: email,
		Role:  role,
	}
	return &out
}

func (r *UserResourceModel) ToDeleteSDKType() *shared.InvitationPostRequest {
	out := r.ToCreateSDKType()
	return out
}

func (r *UserResourceModel) RefreshFromCreateResponse(resp *shared.Invitation) {
	if resp.Email != nil {
		r.Email = types.StringValue(*resp.Email)
	} else {
		r.Email = types.StringNull()
	}
	if resp.ID != nil {
		r.ID = types.StringValue(*resp.ID)
	} else {
		r.ID = types.StringNull()
	}
	if resp.Role != nil {
		r.Role = types.StringValue(string(*resp.Role))
	} else {
		r.Role = types.StringNull()
	}
}
