// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteV1OrganizationsOrganizationIDMembersUserIDRequest struct {
	// ID of the requested organization.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// ID of the requested user.
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

type DeleteV1OrganizationsOrganizationIDMembersUserIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
