// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteV1OrganizationsOrganizationIDKeysKeyIDRequest struct {
	// ID of the key to delete.
	KeyID string `pathParam:"style=simple,explode=false,name=keyId"`
	// ID of the organization that owns the key.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

type DeleteV1OrganizationsOrganizationIDKeysKeyIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
