// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteV1OrganizationsOrganizationIDInvitationsInvitationIDRequest struct {
	// ID of the requested organization.
	InvitationID string `pathParam:"style=simple,explode=false,name=invitationId"`
	// ID of the organization that has the invitation.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

type DeleteV1OrganizationsOrganizationIDInvitationsInvitationIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
