// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteV1OrganizationsOrganizationIDServicesServiceIDRequest struct {
	// ID of the organization that owns the service.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// ID of the service to delete.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
}

type DeleteV1OrganizationsOrganizationIDServicesServiceIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
