// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"clickhouse/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetV1OrganizationsOrganizationIDActivitiesRequest struct {
	// ID of the requested organization.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

// GetV1OrganizationsOrganizationIDActivities400ApplicationJSON - The server cannot or will not process the request due to something that is perceived to be a client error.
type GetV1OrganizationsOrganizationIDActivities400ApplicationJSON struct {
	// Detailed error description.
	Error *string `json:"error,omitempty"`
}

// GetV1OrganizationsOrganizationIDActivities200ApplicationJSON - Successful response
type GetV1OrganizationsOrganizationIDActivities200ApplicationJSON struct {
	Result []shared.Activity `json:"result,omitempty"`
}

type GetV1OrganizationsOrganizationIDActivitiesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	GetV1OrganizationsOrganizationIDActivities200ApplicationJSONObject *GetV1OrganizationsOrganizationIDActivities200ApplicationJSON
	// The server cannot or will not process the request due to something that is perceived to be a client error.
	GetV1OrganizationsOrganizationIDActivities400ApplicationJSONObject *GetV1OrganizationsOrganizationIDActivities400ApplicationJSON
}
