// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type GetV1OrganizationsOrganizationIDServicesServiceIDBackupsRequest struct {
	// ID of the organization that owns the backup.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// ID of the service the backup was created from.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
}

// GetV1OrganizationsOrganizationIDServicesServiceIDBackups400ApplicationJSON - The server cannot or will not process the request due to something that is perceived to be a client error.
type GetV1OrganizationsOrganizationIDServicesServiceIDBackups400ApplicationJSON struct {
	// Detailed error description.
	Error *string `json:"error,omitempty"`
	// HTTP status code.
	Status *float64 `json:"status,omitempty"`
}

// GetV1OrganizationsOrganizationIDServicesServiceIDBackups200ApplicationJSON - Successful response
type GetV1OrganizationsOrganizationIDServicesServiceIDBackups200ApplicationJSON struct {
	Result []shared.Backup `json:"result,omitempty"`
	// HTTP status code.
	Status *float64 `json:"status,omitempty"`
}

type GetV1OrganizationsOrganizationIDServicesServiceIDBackupsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	GetV1OrganizationsOrganizationIDServicesServiceIDBackups200ApplicationJSONObject *GetV1OrganizationsOrganizationIDServicesServiceIDBackups200ApplicationJSON
	// The server cannot or will not process the request due to something that is perceived to be a client error.
	GetV1OrganizationsOrganizationIDServicesServiceIDBackups400ApplicationJSONObject *GetV1OrganizationsOrganizationIDServicesServiceIDBackups400ApplicationJSON
}
