// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"clickhouse/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetV1OrganizationsOrganizationIDInvitationsInvitationIDRequest struct {
	// ID of the requested organization.
	InvitationID string `pathParam:"style=simple,explode=false,name=invitationId"`
	// ID of the requested organization.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

// GetV1OrganizationsOrganizationIDInvitationsInvitationID400ApplicationJSON - The server cannot or will not process the request due to something that is perceived to be a client error.
type GetV1OrganizationsOrganizationIDInvitationsInvitationID400ApplicationJSON struct {
	// Detailed error description.
	Error *string `json:"error,omitempty"`
}

// GetV1OrganizationsOrganizationIDInvitationsInvitationID200ApplicationJSON - Successful response
type GetV1OrganizationsOrganizationIDInvitationsInvitationID200ApplicationJSON struct {
	Result *shared.Invitation `json:"result,omitempty"`
}

type GetV1OrganizationsOrganizationIDInvitationsInvitationIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	GetV1OrganizationsOrganizationIDInvitationsInvitationID200ApplicationJSONObject *GetV1OrganizationsOrganizationIDInvitationsInvitationID200ApplicationJSON
	// The server cannot or will not process the request due to something that is perceived to be a client error.
	GetV1OrganizationsOrganizationIDInvitationsInvitationID400ApplicationJSONObject *GetV1OrganizationsOrganizationIDInvitationsInvitationID400ApplicationJSON
}
