// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"clickhouse/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetV1OrganizationsOrganizationIDActivitiesActivityIDRequest struct {
	// ID of the requested activity.
	ActivityID string `pathParam:"style=simple,explode=false,name=activityId"`
	// ID of the requested organization.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

// GetV1OrganizationsOrganizationIDActivitiesActivityID400ApplicationJSON - The server cannot or will not process the request due to something that is perceived to be a client error.
type GetV1OrganizationsOrganizationIDActivitiesActivityID400ApplicationJSON struct {
	// Detailed error description.
	Error *string `json:"error,omitempty"`
}

// GetV1OrganizationsOrganizationIDActivitiesActivityID200ApplicationJSON - Successful response
type GetV1OrganizationsOrganizationIDActivitiesActivityID200ApplicationJSON struct {
	Result *shared.Activity `json:"result,omitempty"`
}

type GetV1OrganizationsOrganizationIDActivitiesActivityIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	GetV1OrganizationsOrganizationIDActivitiesActivityID200ApplicationJSONObject *GetV1OrganizationsOrganizationIDActivitiesActivityID200ApplicationJSON
	// The server cannot or will not process the request due to something that is perceived to be a client error.
	GetV1OrganizationsOrganizationIDActivitiesActivityID400ApplicationJSONObject *GetV1OrganizationsOrganizationIDActivitiesActivityID400ApplicationJSON
}
