// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"clickhouse/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetV1OrganizationsOrganizationIDServicesServiceIDRequest struct {
	// ID of the organization that owns the service.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// ID of the requested service.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
}

// GetV1OrganizationsOrganizationIDServicesServiceID400ApplicationJSON - The server cannot or will not process the request due to something that is perceived to be a client error.
type GetV1OrganizationsOrganizationIDServicesServiceID400ApplicationJSON struct {
	// Detailed error description.
	Error *string `json:"error,omitempty"`
}

// GetV1OrganizationsOrganizationIDServicesServiceID200ApplicationJSON - Successful response
type GetV1OrganizationsOrganizationIDServicesServiceID200ApplicationJSON struct {
	Result *shared.Service `json:"result,omitempty"`
}

type GetV1OrganizationsOrganizationIDServicesServiceIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	GetV1OrganizationsOrganizationIDServicesServiceID200ApplicationJSONObject *GetV1OrganizationsOrganizationIDServicesServiceID200ApplicationJSON
	// The server cannot or will not process the request due to something that is perceived to be a client error.
	GetV1OrganizationsOrganizationIDServicesServiceID400ApplicationJSONObject *GetV1OrganizationsOrganizationIDServicesServiceID400ApplicationJSON
}
