// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"clickhouse/internal/sdk/pkg/models/shared"
	"net/http"
)

type PatchV1OrganizationsOrganizationIDMembersUserIDRequest struct {
	MemberPatchRequest *shared.MemberPatchRequest `request:"mediaType=application/json"`
	// ID of the organization the member is part of.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// ID of the user to patch
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

// PatchV1OrganizationsOrganizationIDMembersUserID400ApplicationJSON - The server cannot or will not process the request due to something that is perceived to be a client error.
type PatchV1OrganizationsOrganizationIDMembersUserID400ApplicationJSON struct {
	// Detailed error description.
	Error *string `json:"error,omitempty"`
}

// PatchV1OrganizationsOrganizationIDMembersUserID200ApplicationJSON - Successful response
type PatchV1OrganizationsOrganizationIDMembersUserID200ApplicationJSON struct {
	Result *shared.Member `json:"result,omitempty"`
}

type PatchV1OrganizationsOrganizationIDMembersUserIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	PatchV1OrganizationsOrganizationIDMembersUserID200ApplicationJSONObject *PatchV1OrganizationsOrganizationIDMembersUserID200ApplicationJSON
	// The server cannot or will not process the request due to something that is perceived to be a client error.
	PatchV1OrganizationsOrganizationIDMembersUserID400ApplicationJSONObject *PatchV1OrganizationsOrganizationIDMembersUserID400ApplicationJSON
}
