// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"clickhouse/internal/sdk/pkg/models/shared"
	"net/http"
)

type PatchV1OrganizationsOrganizationIDServicesServiceIDPasswordRequest struct {
	ServicePasswordPatchRequest *shared.ServicePasswordPatchRequest `request:"mediaType=application/json"`
	// ID of the organization that owns the service.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// ID of the service to update password.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
}

// PatchV1OrganizationsOrganizationIDServicesServiceIDPassword400ApplicationJSON - The server cannot or will not process the request due to something that is perceived to be a client error.
type PatchV1OrganizationsOrganizationIDServicesServiceIDPassword400ApplicationJSON struct {
	// Detailed error description.
	Error *string `json:"error,omitempty"`
	// HTTP status code.
	Status *float64 `json:"status,omitempty"`
}

// PatchV1OrganizationsOrganizationIDServicesServiceIDPassword200ApplicationJSON - Successful response
type PatchV1OrganizationsOrganizationIDServicesServiceIDPassword200ApplicationJSON struct {
	Result *shared.ServicePasswordPatchResponse `json:"result,omitempty"`
	// HTTP status code.
	Status *float64 `json:"status,omitempty"`
}

type PatchV1OrganizationsOrganizationIDServicesServiceIDPasswordResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	PatchV1OrganizationsOrganizationIDServicesServiceIDPassword200ApplicationJSONObject *PatchV1OrganizationsOrganizationIDServicesServiceIDPassword200ApplicationJSON
	// The server cannot or will not process the request due to something that is perceived to be a client error.
	PatchV1OrganizationsOrganizationIDServicesServiceIDPassword400ApplicationJSONObject *PatchV1OrganizationsOrganizationIDServicesServiceIDPassword400ApplicationJSON
}
