// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type PatchV1OrganizationsOrganizationIDServicesServiceIDStateRequest struct {
	ServiceStatePatchRequest *shared.ServiceStatePatchRequest `request:"mediaType=application/json"`
	// ID of the organization that owns the service.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// ID of the service to update state.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
}

// PatchV1OrganizationsOrganizationIDServicesServiceIDState400ApplicationJSON - The server cannot or will not process the request due to something that is perceived to be a client error.
type PatchV1OrganizationsOrganizationIDServicesServiceIDState400ApplicationJSON struct {
	// Detailed error description.
	Error *string `json:"error,omitempty"`
	// HTTP status code.
	Status *float64 `json:"status,omitempty"`
}

// PatchV1OrganizationsOrganizationIDServicesServiceIDState200ApplicationJSON - Successful response
type PatchV1OrganizationsOrganizationIDServicesServiceIDState200ApplicationJSON struct {
	Result *shared.Service `json:"result,omitempty"`
	// HTTP status code.
	Status *float64 `json:"status,omitempty"`
}

type PatchV1OrganizationsOrganizationIDServicesServiceIDStateResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	PatchV1OrganizationsOrganizationIDServicesServiceIDState200ApplicationJSONObject *PatchV1OrganizationsOrganizationIDServicesServiceIDState200ApplicationJSON
	// The server cannot or will not process the request due to something that is perceived to be a client error.
	PatchV1OrganizationsOrganizationIDServicesServiceIDState400ApplicationJSONObject *PatchV1OrganizationsOrganizationIDServicesServiceIDState400ApplicationJSON
}
