// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"clickhouse/internal/sdk/pkg/models/shared"
	"net/http"
)

type PatchV1OrganizationsOrganizationIDKeysKeyIDRequest struct {
	APIKeyPatchRequest *shared.APIKeyPatchRequest `request:"mediaType=application/json"`
	// ID of the key to update.
	KeyID string `pathParam:"style=simple,explode=false,name=keyId"`
	// ID of the organization that owns the key.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

// PatchV1OrganizationsOrganizationIDKeysKeyID400ApplicationJSON - The server cannot or will not process the request due to something that is perceived to be a client error.
type PatchV1OrganizationsOrganizationIDKeysKeyID400ApplicationJSON struct {
	// Detailed error description.
	Error *string `json:"error,omitempty"`
}

// PatchV1OrganizationsOrganizationIDKeysKeyID200ApplicationJSON - Successful response
type PatchV1OrganizationsOrganizationIDKeysKeyID200ApplicationJSON struct {
	Result *shared.APIKey `json:"result,omitempty"`
}

type PatchV1OrganizationsOrganizationIDKeysKeyIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	PatchV1OrganizationsOrganizationIDKeysKeyID200ApplicationJSONObject *PatchV1OrganizationsOrganizationIDKeysKeyID200ApplicationJSON
	// The server cannot or will not process the request due to something that is perceived to be a client error.
	PatchV1OrganizationsOrganizationIDKeysKeyID400ApplicationJSONObject *PatchV1OrganizationsOrganizationIDKeysKeyID400ApplicationJSON
}
