// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"clickhouse/internal/sdk/pkg/models/shared"
	"net/http"
)

type PatchV1OrganizationsOrganizationIDServicesServiceIDRequest struct {
	ServicePatchRequest *shared.ServicePatchRequest `request:"mediaType=application/json"`
	// ID of the organization that owns the service.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// ID of the service to update.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
}

// PatchV1OrganizationsOrganizationIDServicesServiceID400ApplicationJSON - The server cannot or will not process the request due to something that is perceived to be a client error.
type PatchV1OrganizationsOrganizationIDServicesServiceID400ApplicationJSON struct {
	// Detailed error description.
	Error *string `json:"error,omitempty"`
}

// PatchV1OrganizationsOrganizationIDServicesServiceID200ApplicationJSON - Successful response
type PatchV1OrganizationsOrganizationIDServicesServiceID200ApplicationJSON struct {
	Result *shared.Service `json:"result,omitempty"`
}

type PatchV1OrganizationsOrganizationIDServicesServiceIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	PatchV1OrganizationsOrganizationIDServicesServiceID200ApplicationJSONObject *PatchV1OrganizationsOrganizationIDServicesServiceID200ApplicationJSON
	// The server cannot or will not process the request due to something that is perceived to be a client error.
	PatchV1OrganizationsOrganizationIDServicesServiceID400ApplicationJSONObject *PatchV1OrganizationsOrganizationIDServicesServiceID400ApplicationJSON
}
