// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type PostV1OrganizationsOrganizationIDInvitationsRequest struct {
	InvitationPostRequest *shared.InvitationPostRequest `request:"mediaType=application/json"`
	// ID of the organization to invite a user to.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

// PostV1OrganizationsOrganizationIDInvitations400ApplicationJSON - The server cannot or will not process the request due to something that is perceived to be a client error.
type PostV1OrganizationsOrganizationIDInvitations400ApplicationJSON struct {
	// Detailed error description.
	Error *string `json:"error,omitempty"`
	// HTTP status code.
	Status *float64 `json:"status,omitempty"`
}

// PostV1OrganizationsOrganizationIDInvitations200ApplicationJSON - Successful response
type PostV1OrganizationsOrganizationIDInvitations200ApplicationJSON struct {
	Result *shared.Invitation `json:"result,omitempty"`
	// HTTP status code.
	Status *float64 `json:"status,omitempty"`
}

type PostV1OrganizationsOrganizationIDInvitationsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	PostV1OrganizationsOrganizationIDInvitations200ApplicationJSONObject *PostV1OrganizationsOrganizationIDInvitations200ApplicationJSON
	// The server cannot or will not process the request due to something that is perceived to be a client error.
	PostV1OrganizationsOrganizationIDInvitations400ApplicationJSONObject *PostV1OrganizationsOrganizationIDInvitations400ApplicationJSON
}
