// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"clickhouse/internal/sdk/pkg/models/shared"
	"net/http"
)

type PostV1OrganizationsOrganizationIDKeysRequest struct {
	APIKeyPostRequest *shared.APIKeyPostRequest `request:"mediaType=application/json"`
	// ID of the organization that will own the key.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

// PostV1OrganizationsOrganizationIDKeys400ApplicationJSON - The server cannot or will not process the request due to something that is perceived to be a client error.
type PostV1OrganizationsOrganizationIDKeys400ApplicationJSON struct {
	// Detailed error description.
	Error *string `json:"error,omitempty"`
	// HTTP status code.
	Status *float64 `json:"status,omitempty"`
}

// PostV1OrganizationsOrganizationIDKeys200ApplicationJSON - Successful response
type PostV1OrganizationsOrganizationIDKeys200ApplicationJSON struct {
	Result *shared.APIKeyPostResponse `json:"result,omitempty"`
	// HTTP status code.
	Status *float64 `json:"status,omitempty"`
}

type PostV1OrganizationsOrganizationIDKeysResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	PostV1OrganizationsOrganizationIDKeys200ApplicationJSONObject *PostV1OrganizationsOrganizationIDKeys200ApplicationJSON
	// The server cannot or will not process the request due to something that is perceived to be a client error.
	PostV1OrganizationsOrganizationIDKeys400ApplicationJSONObject *PostV1OrganizationsOrganizationIDKeys400ApplicationJSON
}
