// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"clickhouse/internal/sdk/pkg/models/shared"
	"net/http"
)

type PostV1OrganizationsOrganizationIDServicesRequest struct {
	ServicePostRequest *shared.ServicePostRequest `request:"mediaType=application/json"`
	// ID of the organization that will own the service.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

// PostV1OrganizationsOrganizationIDServices400ApplicationJSON - The server cannot or will not process the request due to something that is perceived to be a client error.
type PostV1OrganizationsOrganizationIDServices400ApplicationJSON struct {
	// Detailed error description.
	Error *string `json:"error,omitempty"`
}

// PostV1OrganizationsOrganizationIDServices200ApplicationJSON - Successful response
type PostV1OrganizationsOrganizationIDServices200ApplicationJSON struct {
	Result *shared.ServicePostResponse `json:"result,omitempty"`
}

type PostV1OrganizationsOrganizationIDServicesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	PostV1OrganizationsOrganizationIDServices200ApplicationJSONObject *PostV1OrganizationsOrganizationIDServices200ApplicationJSON
	// The server cannot or will not process the request due to something that is perceived to be a client error.
	PostV1OrganizationsOrganizationIDServices400ApplicationJSONObject *PostV1OrganizationsOrganizationIDServices400ApplicationJSON
}
